FROM rocker/verse:latest

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libfontconfig1-dev \
    libfreetype6-dev \
    libfribidi-dev \
    libharfbuzz-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    libxml2-dev \
    fonts-dejavu \
    gdebi-core \
    curl

# HTS + compression tools for upstream VCF/gVCF processing
RUN apt-get update && apt-get install -y --no-install-recommends \
    bcftools \
    tabix \
    zstd \
 && rm -rf /var/lib/apt/lists/*

# Install Quarto
RUN curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb && \
    gdebi -n quarto-1.3.450-linux-amd64.deb && \
    rm quarto-1.3.450-linux-amd64.deb

# Install required R packages
RUN R -e "install.packages(c('tidyverse', 'quarto', 'ggridges', 'patchwork', 'DT', 'viridis', 'here', 'showtext', 'ggthemes'), dependencies=TRUE)" && \
    R -e "install.packages('tidyplots', repos = c('https://timcdlucas.r-universe.dev', 'https://cloud.r-project.org'))"

# copying the link from github directly wont work check the url so:
# /tree/ = GitHub web interface (serves HTML pages) (wrong)
# /raw/ = Raw file content (serves the actual binary file) (correct)
# Install FontAwesome
RUN mkdir -p /usr/share/fonts && \
    curl -o /usr/share/fonts/fontawesome-webfont.ttf -L https://github.com/IsmaelHC1994/pgsc_calc_mhi/raw/dev-mhi-hpc/assets/report/fontawesome-webfont.ttf && \
    fc-cache -f -v

# Create working directory with appropriate permissions
RUN mkdir -p /analysis && \
    chmod 777 /analysis

WORKDIR /analysis

# 130 ❯ docker save ismaelhc94/pgsc-mhi-report:latest | bzip2 > ../pgsc-mhi-report_latest.tar.bz2